//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.Wwt.TileGenerator.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.Wwt.TileGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The folder doesn&apos;t exist. Provide a valid path..
        /// </summary>
        public static string ArgumentErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ArgumentErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom Right Latitude.
        /// </summary>
        public static string BottomRightLatitudeLabel
        {
            get
            {
                return ResourceManager.GetString("BottomRightLatitudeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom Right Longitude.
        /// </summary>
        public static string BottomRightLongitudeLabel
        {
            get
            {
                return ResourceManager.GetString("BottomRightLongitudeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bounding Co-ordinates.
        /// </summary>
        public static string BoundingCoordinatesLabel
        {
            get
            {
                return ResourceManager.GetString("BoundingCoordinatesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify the bounding co-ordinates the source imagery represents. By default the imagery represents the entire world..
        /// </summary>
        public static string BoundingCoordinatesToolTip
        {
            get
            {
                return ResourceManager.GetString("BoundingCoordinatesToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string CalculatingLabel
        {
            get
            {
                return ResourceManager.GetString("CalculatingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton
        {
            get
            {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseToolTip
        {
            get
            {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Tiles.
        /// </summary>
        public static string CreateTileGeneratorDescLabel
        {
            get
            {
                return ResourceManager.GetString("CreateTileGeneratorDescLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate Tile Pyramids.
        /// </summary>
        public static string CreateTileGeneratorLabel
        {
            get
            {
                return ResourceManager.GetString("CreateTileGeneratorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsLabel
        {
            get
            {
                return ResourceManager.GetString("CreditsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can specify who you would like to credit for this imagery..
        /// </summary>
        public static string CreditsToolTip
        {
            get
            {
                return ResourceManager.GetString("CreditsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credits URL.
        /// </summary>
        public static string CreditsURLLabel
        {
            get
            {
                return ResourceManager.GetString("CreditsURLLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can specify the URL to the web site of the organization that you would like to credit for this imagery..
        /// </summary>
        public static string CreditsURLToolTip
        {
            get
            {
                return ResourceManager.GetString("CreditsURLToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desired Projection.
        /// </summary>
        public static string DesiredProjectionLabel
        {
            get
            {
                return ResourceManager.GetString("DesiredProjectionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify the spherical projection you would like your output imagery to be in. .
        /// </summary>
        public static string DesiredProjectionToolTip
        {
            get
            {
                return ResourceManager.GetString("DesiredProjectionToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Name*.
        /// </summary>
        public static string FileNameLabel
        {
            get
            {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provide a name for the output WTML file that will be generated. This name will be displayed in WWT..
        /// </summary>
        public static string FileNameToolTip
        {
            get
            {
                return ResourceManager.GetString("FileNameToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file no longer exists..
        /// </summary>
        public static string FileNotFoundError
        {
            get
            {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The output folder no longer exists..
        /// </summary>
        public static string FolderNotFoundError
        {
            get
            {
                return ResourceManager.GetString("FolderNotFoundError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate Plate File.
        /// </summary>
        public static string GeneratePlateLabel
        {
            get
            {
                return ResourceManager.GetString("GeneratePlateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate a plate file to bundle all tiles into a single file. Plate files are perfect for transfering the image tile pyramid set. .
        /// </summary>
        public static string GeneratePlateToolTip
        {
            get
            {
                return ResourceManager.GetString("GeneratePlateToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The current operation cannot be completed. Please try again later..
        /// </summary>
        public static string GenericErrorMessage
        {
            get
            {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image Conversion Details.
        /// </summary>
        public static string ImageConversionLabel
        {
            get
            {
                return ResourceManager.GetString("ImageConversionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Image Dimensions.
        /// </summary>
        public static string ImageDimensionLabel
        {
            get
            {
                return ResourceManager.GetString("ImageDimensionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Image Path.
        /// </summary>
        public static string ImagePathLabel
        {
            get
            {
                return ResourceManager.GetString("ImagePathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provide the location of image that you would like to tile and view in WWT. .
        /// </summary>
        public static string ImagePathToolTip
        {
            get
            {
                return ResourceManager.GetString("ImagePathToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Image Properties.
        /// </summary>
        public static string ImagePropertiesLabel
        {
            get
            {
                return ResourceManager.GetString("ImagePropertiesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use this tool to generate tile pyramids that can be viewed in the WorldWide Telescope..
        /// </summary>
        public static string InputDetailsDescLabel
        {
            get
            {
                return ResourceManager.GetString("InputDetailsDescLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tile Generator.
        /// </summary>
        public static string InputDetailsHeaderLabel
        {
            get
            {
                return ResourceManager.GetString("InputDetailsHeaderLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provide Input Image.
        /// </summary>
        public static string InputDetailsImageLabel
        {
            get
            {
                return ResourceManager.GetString("InputDetailsImageLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        public static string InputDetailsMandatoryLabel
        {
            get
            {
                return ResourceManager.GetString("InputDetailsMandatoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Tile Generator.
        /// </summary>
        public static string InputDetailsWelcomeLabel
        {
            get
            {
                return ResourceManager.GetString("InputDetailsWelcomeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input file could not be found. Please select a valid file and try again..
        /// </summary>
        public static string InputFileNotFoundError
        {
            get
            {
                return ResourceManager.GetString("InputFileNotFoundError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string InputNextButton
        {
            get
            {
                return ResourceManager.GetString("InputNextButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify Output Properties.
        /// </summary>
        public static string InputOutputpropsLabel
        {
            get
            {
                return ResourceManager.GetString("InputOutputpropsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Properties.
        /// </summary>
        public static string InputPropetiesLabel
        {
            get
            {
                return ResourceManager.GetString("InputPropetiesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top left latitude must be more than the bottom right latitude..
        /// </summary>
        public static string InvalidBoundaryLatValError
        {
            get
            {
                return ResourceManager.GetString("InvalidBoundaryLatValError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top left longitude must be lesser than the bottom right longitude..
        /// </summary>
        public static string InvalidBoundaryLongValError
        {
            get
            {
                return ResourceManager.GetString("InvalidBoundaryLongValError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please provide a numeric value..
        /// </summary>
        public static string InvalidDataError
        {
            get
            {
                return ResourceManager.GetString("InvalidDataError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input images in jpg, jpeg, png and tiff format only are supported. Please provide an image in one of these formats..
        /// </summary>
        public static string InvalidImageFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected input file is not valid. Please select a valid file and try again..
        /// </summary>
        public static string InvalidInputFile
        {
            get
            {
                return ResourceManager.GetString("InvalidInputFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image could not be found at the specified location..
        /// </summary>
        public static string InvalidInputImagePath
        {
            get
            {
                return ResourceManager.GetString("InvalidInputImagePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please provide data between -90 to +90.
        /// </summary>
        public static string InvalidLatitudeError
        {
            get
            {
                return ResourceManager.GetString("InvalidLatitudeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please provide data from -180 to +180.
        /// </summary>
        public static string InvalidLongitudeError
        {
            get
            {
                return ResourceManager.GetString("InvalidLongitudeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Number of Levels.
        /// </summary>
        public static string LevelsLabel
        {
            get
            {
                return ResourceManager.GetString("LevelsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The maximum number of levels of the pyramid is suggested for you based on the size of the input image and the area it covers. Decreasing this number is useful when testing as smaller pyramids are naturally quicker to generate..
        /// </summary>
        public static string LevelsToolTip
        {
            get
            {
                return ResourceManager.GetString("LevelsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingContent
        {
            get
            {
                return ResourceManager.GetString("LoadingContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string MandatoryError
        {
            get
            {
                return ResourceManager.GetString("MandatoryError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tile Generator.
        /// </summary>
        public static string MessageBoxCaption
        {
            get
            {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeTooltip
        {
            get
            {
                return ResourceManager.GetString("MinimizeTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotApplicable
        {
            get
            {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton
        {
            get
            {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an input image .
        /// </summary>
        public static string OpenFileDialogTitle
        {
            get
            {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image Files(*.PNG;*.JPG;*.JPEG,*.TIFF,*.TIF)|*.PNG;*.JPG;*.JPEG;*.TIFF;*.TIF.
        /// </summary>
        public static string OpenFileFilter
        {
            get
            {
                return ResourceManager.GetString("OpenFileFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open in WWT.
        /// </summary>
        public static string OpenFileLabel
        {
            get
            {
                return ResourceManager.GetString("OpenFileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select an output folder..
        /// </summary>
        public static string OpenFolderDialogDesc
        {
            get
            {
                return ResourceManager.GetString("OpenFolderDialogDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Folder Location.
        /// </summary>
        public static string OpenFolderLocationLabel
        {
            get
            {
                return ResourceManager.GetString("OpenFolderLocationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image exceeds the size limit. Please try uploading a new image. .
        /// </summary>
        public static string OutOfMemoryMessage
        {
            get
            {
                return ResourceManager.GetString("OutOfMemoryMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string OutputBackButton
        {
            get
            {
                return ResourceManager.GetString("OutputBackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Collection Details.
        /// </summary>
        public static string OutputCollectionLabel
        {
            get
            {
                return ResourceManager.GetString("OutputCollectionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string OutputCreateButton
        {
            get
            {
                return ResourceManager.GetString("OutputCreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provide Output Details.
        /// </summary>
        public static string OutputDetailsLabel
        {
            get
            {
                return ResourceManager.GetString("OutputDetailsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output filename can&apos;t contain any of the following characters :
        ///\ / : * ? &quot;  |  &lt; &gt;.
        /// </summary>
        public static string OutputFilenameInvalidCharacterError
        {
            get
            {
                return ResourceManager.GetString("OutputFilenameInvalidCharacterError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Folder Path.
        /// </summary>
        public static string OutputFolderLabel
        {
            get
            {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modify your output tile pyramid settings..
        /// </summary>
        public static string OutputInfoLabel
        {
            get
            {
                return ResourceManager.GetString("OutputInfoLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output path contains invalid characters..
        /// </summary>
        public static string OutputPathInvalidCharacterError
        {
            get
            {
                return ResourceManager.GetString("OutputPathInvalidCharacterError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Output Folder Path*.
        /// </summary>
        public static string OutputPathLabel
        {
            get
            {
                return ResourceManager.GetString("OutputPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can specify where you would like the tile pyramids to be generated. By default they will be generated in your ProgramData folder..
        /// </summary>
        public static string OutputPathToolTip
        {
            get
            {
                return ResourceManager.GetString("OutputPathToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The folder path is too long..
        /// </summary>
        public static string PathTooLongErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PathTooLongErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string ProcessingText
        {
            get
            {
                return ResourceManager.GetString("ProcessingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ProgressBarErrorTag
        {
            get
            {
                return ResourceManager.GetString("ProgressBarErrorTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string ProgressBarProcessingTag
        {
            get
            {
                return ResourceManager.GetString("ProgressBarProcessingTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ProgressBarSuccessTag
        {
            get
            {
                return ResourceManager.GetString("ProgressBarSuccessTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProgressCancelButton
        {
            get
            {
                return ResourceManager.GetString("ProgressCancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ProgressCloseButton
        {
            get
            {
                return ResourceManager.GetString("ProgressCloseButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart Tiling.
        /// </summary>
        public static string ProgressResetButton
        {
            get
            {
                return ResourceManager.GetString("ProgressResetButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string ProgressStartOverButton
        {
            get
            {
                return ResourceManager.GetString("ProgressStartOverButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Progress Update.
        /// </summary>
        public static string ProgressUpdateLabel
        {
            get
            {
                return ResourceManager.GetString("ProgressUpdateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pyramid generation was successfully completed in {0:D} seconds..
        /// </summary>
        public static string PyramidGenerationCompletedMessage
        {
            get
            {
                return ResourceManager.GetString("PyramidGenerationCompletedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was an error while generating the pyramid. Please try again later..
        /// </summary>
        public static string PyramidGenerationErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PyramidGenerationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image could not be processed due to memory limitation.   .
        /// </summary>
        public static string PyramidGenerationOutOfMemoryMessage
        {
            get
            {
                return ResourceManager.GetString("PyramidGenerationOutOfMemoryMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to *Required Fields.
        /// </summary>
        public static string RequiredLabel
        {
            get
            {
                return ResourceManager.GetString("RequiredLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The folder is not accessible..
        /// </summary>
        public static string SecurityErrorMessage
        {
            get
            {
                return ResourceManager.GetString("SecurityErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source Image Projection.
        /// </summary>
        public static string SourceProjectionLabel
        {
            get
            {
                return ResourceManager.GetString("SourceProjectionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify the projection your source imagery is in..
        /// </summary>
        public static string SourceProjectionToolTip
        {
            get
            {
                return ResourceManager.GetString("SourceProjectionToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string StepCompleted
        {
            get
            {
                return ResourceManager.GetString("StepCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading image.
        /// </summary>
        public static string StepLoadingImage
        {
            get
            {
                return ResourceManager.GetString("StepLoadingImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating plate file.
        /// </summary>
        public static string StepPlateFileGeneration
        {
            get
            {
                return ResourceManager.GetString("StepPlateFileGeneration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating tiles.
        /// </summary>
        public static string StepPyramidGeneration
        {
            get
            {
                return ResourceManager.GetString("StepPyramidGeneration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string StepStarted
        {
            get
            {
                return ResourceManager.GetString("StepStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating thumbnail image.
        /// </summary>
        public static string StepThumbnailGeneration
        {
            get
            {
                return ResourceManager.GetString("StepThumbnailGeneration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating WTML file.
        /// </summary>
        public static string StepWTMLFileCreate
        {
            get
            {
                return ResourceManager.GetString("StepWTMLFileCreate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0 Sec.
        /// </summary>
        public static string TileCompletedTime
        {
            get
            {
                return ResourceManager.GetString("TileCompletedTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tile Generator.
        /// </summary>
        public static string TileGeneratorLabel
        {
            get
            {
                return ResourceManager.GetString("TileGeneratorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time .
        /// </summary>
        public static string TimeLabel
        {
            get
            {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Estimated Time Remaining : .
        /// </summary>
        public static string TimeRemainingLabel
        {
            get
            {
                return ResourceManager.GetString("TimeRemainingLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top Left Latitude.
        /// </summary>
        public static string TopLeftLatitudeLabel
        {
            get
            {
                return ResourceManager.GetString("TopLeftLatitudeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top Left Longitude.
        /// </summary>
        public static string TopLeftLongitudeLabel
        {
            get
            {
                return ResourceManager.GetString("TopLeftLongitudeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tile generation was cancelled by user..
        /// </summary>
        public static string UserCancelledErrorMessage
        {
            get
            {
                return ResourceManager.GetString("UserCancelledErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What&apos;s this?.
        /// </summary>
        public static string WhatsThisText
        {
            get
            {
                return ResourceManager.GetString("WhatsThisText", resourceCulture);
            }
        }
    }
}
